/* Autogenerated Main File */

public class Main {
	public static void main(String[] args) {
		System.out.println(" -----*/* AUTOGENERATED MESSAGE *\\*----- ");
		System.out.println("Create instances of your objects here");
		System.out.println("and run their main methods, passing args");
		System.out.println(" -----*/* AUTOGENERATED MESSAGE *\\*----- ");
	}
}
