/* Autogenerated Main File */
#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf(" -----*/* AUTOGENERATED MESSAGE *\\*----- \n");
    printf("Call your functions here and pass the args\n");
    printf("to those functions if they require them\n");
    printf(" -----*/* AUTOGENERATED MESSAGE *\\*----- \n");
	return 0;
}