/* Autogenerated Main File */
using System;

public class Program
{
    public static void Main()
    {
        Console.WriteLine(" -----*/* AUTOGENERATED MESSAGE *\\*----- ");
        Console.WriteLine("Create instances of your objects here");
        Console.WriteLine("and run their main methods, passing args");
        Console.WriteLine(" -----*/* AUTOGENERATED MESSAGE *\\*----- ");
    }
}
